In [13]:
import pandas as pd
from sklearn import model_selection
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix


In [3]:
matches_cleaned_data = pd.read_csv('./Dataset/matches_cleaned.csv')
matches_df = matches_cleaned_data[['team1', 'team2', 'city', 'toss_winner', 'toss_decision', 'winner']]

In [5]:
array = matches_df.values
x = array[:, 0:5]
y = array[:, 5]
validation_size = 0.10
seed = 7
x_train, x_validation, y_train, y_validation = model_selection.train_test_split(x, y,
                                                                test_size=validation_size,random_state=seed)

In [20]:
knn = DecisionTreeClassifier()
knn.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [9]:
y_predict = knn.predict(x_validation)

In [15]:
y_predict, y_validation

(array([11,  4, 10,  6,  8,  4,  4,  6,  1,  4,  1,  5,  6,  5, 11,  6, 11,
         4,  5, 15,  5, 12,  5,  8, 11,  5,  5,  5, 15,  3,  6,  5, 11,  5,
         6,  5,  5,  8, 11, 15,  8,  1,  1,  2,  1,  7,  2,  2,  1,  6,  3,
         4, 12,  3,  5,  4,  8,  7,  4,  2,  8,  5, 15,  2, 11,  4,  1,  5,
         4,  2,  6,  8,  2,  4,  2,  5,  8, 11,  3,  4,  2,  2],
       dtype=int64),
 array([11,  4,  2,  1, 10,  4,  3,  1,  1,  4,  2,  6, 28,  2, 11,  4,  1,
         4,  5,  8, 10,  4,  4,  8, 11,  5,  5,  3, 14,  3,  6,  7, 11,  5,
         6, 11,  5,  3, 11, 11,  8,  1,  2,  2,  8,  8,  3,  2,  1,  5, 10,
         4,  2, 11,  5,  4,  1,  7,  4,  6,  8, 11,  4,  2, 11,  5,  2,  2,
         4,  1,  6,  1,  2,  4,  1,  3,  8,  6,  1,  4,  3,  2],
       dtype=int64))

In [37]:
print(f1_score(y_validation, y_predict, average="macro"))
print(precision_score(y_validation, y_predict, average="macro"))
print(recall_score(y_validation, y_predict, average="macro")) 

0.3119642262499405
0.32227891156462585
0.3191403834260977


C:\Users\dhruvKP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\dhruvKP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\dhruvKP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\dhruvKP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [32]:
results =[8, 10, 8, 10, 2]
predictions = knn.predict_proba([results])

In [33]:
predictions

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [35]:
score = accuracy_score(y_validation, y_predict)

In [36]:
score

0.47560975609756095

In [38]:
!pip install pycaret

  Using cached cufflinks-0.17.3.tar.gz (81 kB)
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
  Using cached imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
  Using cached htmlmin-0.1.12.tar.gz (19 kB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.3.0 requires scipy==1.4.1, but you have scipy 1.5.4 which is incompatible.
You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.


  Using cached missingno-0.4.2-py3-none-any.whl (9.7 kB)
  Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
  Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metada